nyetbot {
  ollama {
    summarize-user {
      profile-max-chars = 300
      summary-max-chars = 500

      model-config = ${nyetbot.ollama.model-defaults}

      model-config {
        num-predict = 256
      }
      rewrite-model-config = ${nyetbot.ollama.model-defaults}

      rewrite-model-config {
        num-predict = 200
      }
    }
  }
}
