nyetbot {
  ollama {
    context {
      topic {
        enabled        = true
        context-window = 10

        model-config = ${nyetbot.ollama.model-defaults}

        model-config {
          num-predict = 160
        }
      }
    }
  }
}
