nyetbot {
  ollama {
    context {
      register {
        enabled = true

        model-config = ${nyetbot.ollama.model-defaults}

        model-config {
          num-predict = 6
        }
      }
    }
  }
}
