nyetbot {
  ollama {
    context {
      intent {
        enabled = true

        model-config = ${nyetbot.ollama.model-defaults}

        model-config {
          num-predict = 4
        }
      }
    }
  }
}
